import { NextRequest, NextResponse } from "next/server";
import { validateShortenRequest } from "@/lib/validations/url";
import { encodeId } from "@/lib/utils/sqids";
import { normalizeUrl } from "@/lib/utils/url";
import { generateRandomString } from "@/lib/utils/random";
import { checkUrlSafety } from "@/lib/api/safe-browsing";
import { getDb, AppEnv } from "@/db";
import { urls } from "@/db/schema/urls";
import { eq } from "drizzle-orm";
import { trace, SpanStatusCode } from "@opentelemetry/api";
import { setUserAttributes } from "@/lib/utils/telemetry";
import { getCloudflareContext } from "@opennextjs/cloudflare";

// Env is defined in worker-configuration.d.ts (generated by wrangler types)

const tracer = trace.getTracer("url-shortener");



export async function POST(request: NextRequest) {
  return tracer.startActiveSpan("shorten-url", async (span) => {
    try {
      await setUserAttributes(span, request);
      const body = (await request.json()) as { url?: string };
      const result = validateShortenRequest(body);

      if (!result.success) {
        return NextResponse.json(
          { error: result.error.errors[0].message },
          { status: 400 }
        );
      }

      const { url: originalUrl } = result.data;
      const url = normalizeUrl(originalUrl);
      const { env } = (await getCloudflareContext()) as unknown as { env: AppEnv };
      const db = getDb(env);
      const KV = env.URL_CACHE;

      // 既存のURLをチェック
      const existing = await db.query.urls.findFirst({
        where: eq(urls.longUrl, url),
      });

      if (existing) {
        span.setAttribute("short_code", existing.shortCode);
        span.setAttribute("is_existing", true);
        // キャッシュも更新しておく
        if (KV) {
          await KV.put(existing.shortCode, url, { expirationTtl: 86400 });
        }
        const response = NextResponse.json(
          { shortCode: existing.shortCode },
          { status: 200 }
        );
        span.setStatus({ code: SpanStatusCode.OK });
        return response;
      }

      // 安全確認
      const safetyResult = await checkUrlSafety(url);
      if (!safetyResult.safe) {
        return NextResponse.json(
          { error: "このURLは安全ではない可能性があるため登録できません" },
          { status: 403 }
        );
      }

      // 新しいURLを登録（D1はトランザクションをサポートしないため個別に実行）
      // 一時的なコードで挿入してIDを取得
      const [inserted] = await db
        .insert(urls)
        .values({
          longUrl: url,
          shortCode: `tmp-${Date.now()}-${generateRandomString(12)}`,
        })
        .returning({ id: urls.id });

      const shortCode = encodeId(inserted.id);

      // 実際の短縮コードで更新
      await db
        .update(urls)
        .set({ shortCode })
        .where(eq(urls.id, inserted.id));

      // キャッシュを書き込み
      if (KV) {
        await KV.put(shortCode, url, { expirationTtl: 86400 });
      }

      span.setAttribute("short_code", shortCode);
      span.setAttribute("is_existing", false);
      const response = NextResponse.json({ shortCode, url }, { status: 201 });
      span.setStatus({ code: SpanStatusCode.OK });
      return response;
    } catch (error) {
      span.recordException(error as Error);
      span.setStatus({
        code: SpanStatusCode.ERROR,
        message: error instanceof Error ? error.message : "Unknown error",
      });
      console.error("URL shortening error:", error);
      return NextResponse.json(
        { error: "URLの短縮に失敗しました" },
        { status: 500 }
      );
    } finally {
      span.end();
    }
  });
}
